# Generated by Django 4.2.6 on 2023-11-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_boletim', models.CharField(db_column='num_boletim', max_length=255, unique=True)),
                ('data_hora_boletim', models.DateTimeField(db_column='data_hora_boletim')),
                ('No_envolvido', models.IntegerField(db_column='Nº_envolvido')),
                ('condutor', models.CharField(db_column='condutor', max_length=255)),
                ('cod_severidade', models.IntegerField(db_column='cod_severidade')),
                ('desc_severidade', models.CharField(db_column='desc_severidade', max_length=255)),
                ('sexo', models.CharField(db_column='sexo', max_length=255)),
                ('cinto_seguranca', models.CharField(db_column='cinto_seguranca', max_length=255)),
                ('Embreagues', models.CharField(db_column='Embreagues', max_length=255)),
                ('Idade', models.IntegerField(db_column='Idade')),
                ('nascimento', models.DateField(db_column='nascimento')),
                ('categoria_habilitacao', models.CharField(db_column='categoria_habilitacao', max_length=255)),
                ('descricao_habilitacao', models.CharField(db_column='descricao_habilitacao', max_length=255)),
                ('declaracao_obito', models.CharField(db_column='declaracao_obito', max_length=255)),
                ('cod_severidade_antiga', models.CharField(db_column='cod_severidade_antiga', max_length=255)),
                ('especie_veiculo', models.CharField(db_column='especie_veiculo', max_length=255)),
                ('pedestre', models.CharField(db_column='pedestre', max_length=255)),
                ('passageiro', models.CharField(db_column='passageiro', max_length=255)),
            ],
        ),
    ]
