# Generated by Django 4.2.6 on 2023-11-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acidente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acidente',
            table='acidente',
        ),
    ]
