# Generated by Django 4.2.6 on 2023-11-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_acidente_id_alter_acidente_data_hora_boletim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidente',
            name='num_boletim',
            field=models.CharField(db_column='num_boletim', max_length=255),
        ),
    ]
